"""initial schema with all models

Revision ID: 860c7c51edc7
Revises: 
Create Date: 2026-03-24 14:57:08.633550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860c7c51edc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('owner_encrypted_key', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'owner_encrypted_key')
    # ### end Alembic commands ###
